const FAQS = [
  {
    title: 'What is the difference between $FNX and $veFNX?',
    // eslint-disable-next-line max-len
    description:
      "$FNX is Lynex's ERC-20 utility token, enabling transactions and interactions within our ecosystem." +
      ' $veFNX, on the other hand, is the vote-escrow version of $FNX, an ERC-721 governance token in the form of an NFT (non-fungible token).' +
      ' Holders can exercise voting rights in weekly pool elections and earn a proportionate share of the trading fees and incentives tied to their chosen pools.',
  },
  {
    title: 'What does it mean that the $veFNX is locked?',
    // eslint-disable-next-line max-len
    description:
      '$veFNX represents $FNX tokens that have been time-locked. As a $veFNX holder, you retain complete ownership and can utilize its governance power. After the locked period, you can redeem your $veFNX back to the freely tradable $FNX.',
  },
  {
    title: 'What are the benefits o the $veFNX token?',
    // eslint-disable-next-line max-len
    description:
      '$veFNX holders can vote for gauges weekly, and access 100% of the trading fees and bribes for the associated pool. Also, ' +
      'they can partake in governance and cast votes for the protocol improvement proposals. $veFNX voters receive: Trading fees generated by the pool(s) they vote for Bribes deposited for the pools they vote for Weekly $veFNX distribution (rebase)',
  },
  {
    title: 'When can I claim my tokens?',
    description: 'You can claim your tokens on February the 15th, one day after the public sale ends.',
  },
]

export default FAQS
